#!/bin/sh

set shell zsh
set shellopts '-euy'
set ifs "\n"
set scrolloff 10
set drawbox
set icons
set period 1
set hiddenfiles ".*:*.aux:*.log:*.bbl:*.bcf:*.blg:*.run.xml"
set previewer ~/.config/lf/preview

cmd open ${{
    test -L $f && f=$(readlink -f $f)
    case $(file --mime-type $f -b) in
        text/*) $EDITOR $fx;;
        video/*) vlc $f;;
        image/vnd.djvu|application/pdf|application/octet-stream|application/postscript|application/pdf|application/epub*) $BROWSER "$fx" ;;
        *) for f in $fx; do setsid $OPENER $f > /dev/null 2> /dev/null & done;;
    esac
}}

# move current file or selected files to trash folder
# (also see 'man mv' for backup/overwrite options)
cmd trash %set -f; mv $fx ~/.trash

# define a custom 'delete' command
cmd delete ${{
    set -f
    printf "$fx\n"
    printf "delete?[y/n]"
    read ans
    [ $ans = "y" ] && rm -rf $fx
}}

# use '<delete>' key for either 'trash' or 'delete' command
# map <delete> trash

cmd extract ${{
    set -f
    unar $f
}}

map <enter> shell
map <delete> delete
map x $$f
map X !$f
map ee $$EDITOR "$f"
map D trash
map o &mimeopen $f
map O $mimeopen --ask $f
map ZZ quit

# Shortcuts
source "~/.config/lf/shortcutrc"
