#!/usr/bin/env bash

USER_APPS=""

ROOT_APPS="
alacritty,
k9s,
karabiner,
lazydocker,
lazygit,
lf,
lvim,
shell,
zsh,
skhd,
yabai,
yamllint,
backup,
bin,
btop,
asdf,
bat,
git
"

ROOT_APPS=$ROOT_APPS USER_APPS=$USER_APPS $(dirname $(realpath $0))/install "$@"
