#!/usr/bin/env bash

USER_APPS=""

ROOT_APPS="
alacritty,
k9s,
karabiner,
lazydocker,
lazygit,
lf,
lvim,
nvim,
shell,
skhd,
yabai,
yamllint,
zsh,
backup,
bin,
asdf
"

ROOT_APPS=$ROOT_APPS USER_APPS=$USER_APPS $(dirname $(realpath $0))/install "$@"
