#!/bin/zsh

# Default programs:
export EDITOR="lvim"
export VISUAL="lvim"
export TERMINAL="alacritty"
export BROWSER="open-browser"

# ~/ Clean-up:
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export WORK_HOME="$HOME/Work"
export WAKATIME_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/wakatime"
export XINITRC="${XDG_CONFIG_HOME:-$HOME/.config}/x11/xinitrc"
export NOTMUCH_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/notmuch-config"
export GTK2_RC_FILES="${XDG_CONFIG_HOME:-$HOME/.config}/gtk-2.0/gtkrc-2.0"
export THEMESWITCH_CONFIG_PATH="${XDG_CONFIG_HOME:-$HOME/.config}/themeswitch/config"
export LESSHISTFILE="-"
export NETRC="${XDG_CONFIG_HOME:-$HOME/.config}/net/netrc"
export WGETRC="${XDG_CONFIG_HOME:-$HOME/.config}/wget/wgetrc"
export INPUTRC="${XDG_CONFIG_HOME:-$HOME/.config}/shell/inputrc"
export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"
#export ALSA_CONFIG_PATH="$XDG_CONFIG_HOME/alsa/asoundrc"
#export GNUPGHOME="${XDG_DATA_HOME:-$HOME/.local/share}/gnupg"
export WINEPREFIX="${XDG_DATA_HOME:-$HOME/.local/share}/wineprefixes/default"
export KODI_DATA="${XDG_DATA_HOME:-$HOME/.local/share}/kodi"
export PASSWORD_STORE_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/password-store"
export TMUX_TMPDIR="$XDG_RUNTIME_DIR"
export ANDROID_SDK_HOME="${XDG_CONFIG_HOME:-$HOME/.config}/android"
export CARGO_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/cargo"
export GOPATH="${XDG_DATA_HOME:-$HOME/.local/share}/go"
export ANSIBLE_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/ansible/ansible.cfg"
export UNISON="${XDG_DATA_HOME:-$HOME/.local/share}/unison"
export HISTFILE="${XDG_DATA_HOME:-$HOME/.local/share}/history"
export WEECHAT_HOME="${XDG_CONFIG_HOME:-$HOME/.config}/weechat"
export MBSYNCRC="${XDG_CONFIG_HOME:-$HOME/.config}/mbsync/config"
export ELECTRUMDIR="${XDG_DATA_HOME:-$HOME/.local/share}/electrum"
export ANSIBLE_INVENTORY="${XDG_CONFIG_HOME:-$HOME/.config}/ansible/static-inventory.ini"
export DENO_INSTALL="${XDG_DATA_HOME:-$HOME/.local/share}/deno"

export DOCKER_DEFAULT_PLATFORM="linux/amd64"  

export ZSH_DOTENV_PROMPT=false
export ZSH_DOTENV_FILE=".env.contracts"

export NEOVIDE_FRAMELESS=true
export NEOVIDE_MULTIGRID=true
export NEOVIDE_FRAME=none


# This is the list for lf icons:
source "${XDG_CONFIG_HOME:-$HOME/.config}/lf/icons"
[ ! -f ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ] && shortcutsg >/dev/null 2>&1 &

path=(
  /usr/local/{bin,sbin}
  /opt/homebrew/bin
  /opt/homebrew/opt/openjdk/bin 
  $HOME/.poetry/bin
  $HOME/.emacs.d/bin
  $CARGO_HOME/bin
  $DENO_INSTALL/bin
  $GOPATH/bin
  $path
)

# Adds `~/.local/bin` to $PATH
paths=$(find -L ~/.local/bin -type d -print | xargs printf -- '%s:')%%:
export PATH="$PATH:${paths}"

# Adds yarn global modules to $PATH
export PATH="$(yarn global bin):$PATH"

export PATH="/opt/homebrew/opt/coreutils/libexec/gnubin:$PATH"
export PATH="/opt/homebrew/opt/util-linux/bin:$PATH"
export PATH="/opt/homebrew/opt/util-linux/sbin:$PATH"
export PATH="/opt/homebrew/opt/gnu-sed/libexec/gnubin:$PATH"
